/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query GetEvents {\n    events {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      \n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetEventsDocument,
    "\n  query GetEventById($id: ID!) {\n    event(id: $id) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetEventByIdDocument,
    "\n  query GetEventBySlug($slug: String!) {\n    eventBySlug(slug: $slug) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetEventBySlugDocument,
    "\n  mutation CreateEvent($input: CreateEventInput!) {\n    createEvent(input: $input) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.CreateEventDocument,
    "\n  mutation UpdateEvent($id: ID!, $input: UpdateEventInput!) {\n    updateEvent(id: $id, input: $input) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UpdateEventDocument,
    "\n  mutation DeleteEvent($id: ID!) {\n    deleteEvent(id: $id)\n  }\n": typeof types.DeleteEventDocument,
    "\n  query GetPage($id: ID!) {\n    page(id: $id) {\n      id\n      slug\n      name\n      published\n      publishedAt\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetPageDocument,
    "\n  query GetPages {\n    pages {\n      id\n      slug\n      name\n      published\n      publishedAt\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetPagesDocument,
    "\n  mutation PublishPage($id: ID!) {\n    publishPage(id: $id) { id slug published publishedAt }\n  }\n": typeof types.PublishPageDocument,
    "\n  mutation UpdatePage($id: ID!, $input: UpdatePageInput!) {\n    updatePage(id: $id, input: $input) {\n      id\n      slug\n      name\n      published\n      sections { id builderId type order }\n    }\n  }\n": typeof types.UpdatePageDocument,
    "\n  query GetUsers {\n    users {\n      id\n      name\n      email\n      image\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetUsersDocument,
    "\n  mutation CreatePage($input: CreatePageInput!) {\n    createPage(input: $input) {\n      id\n      slug\n      name\n      published\n      sections { id builderId type order }\n    }\n  }\n": typeof types.CreatePageDocument,
};
const documents: Documents = {
    "\n  query GetEvents {\n    events {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      \n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetEventsDocument,
    "\n  query GetEventById($id: ID!) {\n    event(id: $id) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetEventByIdDocument,
    "\n  query GetEventBySlug($slug: String!) {\n    eventBySlug(slug: $slug) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetEventBySlugDocument,
    "\n  mutation CreateEvent($input: CreateEventInput!) {\n    createEvent(input: $input) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": types.CreateEventDocument,
    "\n  mutation UpdateEvent($id: ID!, $input: UpdateEventInput!) {\n    updateEvent(id: $id, input: $input) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": types.UpdateEventDocument,
    "\n  mutation DeleteEvent($id: ID!) {\n    deleteEvent(id: $id)\n  }\n": types.DeleteEventDocument,
    "\n  query GetPage($id: ID!) {\n    page(id: $id) {\n      id\n      slug\n      name\n      published\n      publishedAt\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetPageDocument,
    "\n  query GetPages {\n    pages {\n      id\n      slug\n      name\n      published\n      publishedAt\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetPagesDocument,
    "\n  mutation PublishPage($id: ID!) {\n    publishPage(id: $id) { id slug published publishedAt }\n  }\n": types.PublishPageDocument,
    "\n  mutation UpdatePage($id: ID!, $input: UpdatePageInput!) {\n    updatePage(id: $id, input: $input) {\n      id\n      slug\n      name\n      published\n      sections { id builderId type order }\n    }\n  }\n": types.UpdatePageDocument,
    "\n  query GetUsers {\n    users {\n      id\n      name\n      email\n      image\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetUsersDocument,
    "\n  mutation CreatePage($input: CreatePageInput!) {\n    createPage(input: $input) {\n      id\n      slug\n      name\n      published\n      sections { id builderId type order }\n    }\n  }\n": types.CreatePageDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetEvents {\n    events {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      \n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetEvents {\n    events {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      \n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetEventById($id: ID!) {\n    event(id: $id) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetEventById($id: ID!) {\n    event(id: $id) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetEventBySlug($slug: String!) {\n    eventBySlug(slug: $slug) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetEventBySlug($slug: String!) {\n    eventBySlug(slug: $slug) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateEvent($input: CreateEventInput!) {\n    createEvent(input: $input) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateEvent($input: CreateEventInput!) {\n    createEvent(input: $input) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateEvent($id: ID!, $input: UpdateEventInput!) {\n    updateEvent(id: $id, input: $input) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateEvent($id: ID!, $input: UpdateEventInput!) {\n    updateEvent(id: $id, input: $input) {\n      id\n      slug\n      title\n      description\n      startDate\n      startTime\n      endDate\n      endTime\n      category {\n        type\n        description\n      }\n      is_featured\n      location {\n        venue\n        address\n        city\n        coordinates {\n          lat\n          lng\n        }\n      }\n      organizer {\n        name\n        email\n        phone\n      }\n      theme {\n        primaryColor\n        secondaryColor\n        accentColor\n        backgroundColor\n        textColor\n        fontFamily\n        layout\n        gradientEnabled\n        gradientDirection\n      }\n      ticketTiers {\n        id\n        name\n        price\n        currency\n        quantity\n        soldCount\n        description\n        available\n      }\n      images {\n        banner\n        gallery\n      }\n      features {\n        showGallery\n        allowGuestUploads\n        showChat\n        showCollaborators\n      }\n      collaborators {\n        name\n        type\n        avatar\n      }\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteEvent($id: ID!) {\n    deleteEvent(id: $id)\n  }\n"): (typeof documents)["\n  mutation DeleteEvent($id: ID!) {\n    deleteEvent(id: $id)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPage($id: ID!) {\n    page(id: $id) {\n      id\n      slug\n      name\n      published\n      publishedAt\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetPage($id: ID!) {\n    page(id: $id) {\n      id\n      slug\n      name\n      published\n      publishedAt\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPages {\n    pages {\n      id\n      slug\n      name\n      published\n      publishedAt\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetPages {\n    pages {\n      id\n      slug\n      name\n      published\n      publishedAt\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation PublishPage($id: ID!) {\n    publishPage(id: $id) { id slug published publishedAt }\n  }\n"): (typeof documents)["\n  mutation PublishPage($id: ID!) {\n    publishPage(id: $id) { id slug published publishedAt }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdatePage($id: ID!, $input: UpdatePageInput!) {\n    updatePage(id: $id, input: $input) {\n      id\n      slug\n      name\n      published\n      sections { id builderId type order }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdatePage($id: ID!, $input: UpdatePageInput!) {\n    updatePage(id: $id, input: $input) {\n      id\n      slug\n      name\n      published\n      sections { id builderId type order }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetUsers {\n    users {\n      id\n      name\n      email\n      image\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetUsers {\n    users {\n      id\n      name\n      email\n      image\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreatePage($input: CreatePageInput!) {\n    createPage(input: $input) {\n      id\n      slug\n      name\n      published\n      sections { id builderId type order }\n    }\n  }\n"): (typeof documents)["\n  mutation CreatePage($input: CreatePageInput!) {\n    createPage(input: $input) {\n      id\n      slug\n      name\n      published\n      sections { id builderId type order }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;